/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const batch: typeof import('@preact/signals-react').batch
  const computed: typeof import('@preact/signals-react').computed
  const createRef: typeof import('react').createRef
  const effect: typeof import('@preact/signals-react').effect
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const signal: typeof import('@preact/signals-react').signal
  const startTransition: typeof import('react').startTransition
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInfiniteQuery: typeof import('@tanstack/react-query').useInfiniteQuery
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useIsFetching: typeof import('@tanstack/react-query').useIsFetching
  const useIsMutating: typeof import('@tanstack/react-query').useIsMutating
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocation: typeof import('react-router-dom').useLocation
  const useMatch: typeof import('react-router-dom').useMatch
  const useMemo: typeof import('react').useMemo
  const useMutation: typeof import('@tanstack/react-query').useMutation
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useParams: typeof import('react-router-dom').useParams
  const useQueries: typeof import('@tanstack/react-query').useQueries
  const useQuery: typeof import('@tanstack/react-query').useQuery
  const useQueryClient: typeof import('@tanstack/react-query').useQueryClient
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useSignal: typeof import('@preact/signals-react').useSignal
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
